POST http://localhost:3001/api/votes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJMb2dpblVzZXIiLCJpYXQiOjE3NzYyNDY4MTV9.fIefXpfS-YSAkA0PQN-Irw_p7MLqUHCnFvvH2PVEHa0

{
  "title": "My Vote Title",
  "expirationDate": "2026-04-21T12:05:03.000Z",
  "options": [
    { "text": "Opt1" },
    { "text": "Opt2" }
  ]
}