name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write

env: 
  NEEDS_DEPLOY: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '25'
      - name: Install dependencies
        run: npm run install:all
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      - name: Trigger deployment
        if: ${{ env.NEEDS_DEPLOY == 'true'}}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_SERVICE_KEY}} 

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch